<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.task6</groupId>
    <artifactId>task6-dockerswarm-app</artifactId>
    <version>1.0.0</version>
    <packaging>war</packaging>

    <name>Task 6 - Docker Swarm Deploy</name>
    <description>Sample Java Web App deployed via Docker Swarm, Nexus &amp; Jenkins</description>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!-- Servlet API (provided by Tomcat) -->
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>4.0.1</version>
            <scope>provided</scope>
        </dependency>

        <!-- JSP API (provided by Tomcat) -->
        <dependency>
            <groupId>javax.servlet.jsp</groupId>
            <artifactId>javax.servlet.jsp-api</artifactId>
            <version>2.3.3</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <pluginRepositories>
        <pluginRepository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
        </pluginRepository>
    </pluginRepositories>
    <build>
        <finalName>task6-app</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.2.0</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.3.2</version>
            </plugin>
        </plugins>
    </build>

    <!-- Nexus Repository Configuration -->
    <distributionManagement>
        <!-- WAR artifacts → maven-swarm repo -->
        <repository>
            <id>maven-swarm</id>
            <url>http://nexus:8081/repository/maven-swarm/</url>
        </repository>
        <snapshotRepository>
            <id>maven-swarm-snapshots</id>
            <url>http://nexus:8081/repository/maven-swarm/</url>
        </snapshotRepository>
    </distributionManagement>

</project>
